//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thu_project2_cnt1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANGCT
    {
        public int MaChiTiet { get; set; }
        public int MaDonHang { get; set; }
        public int MaHang { get; set; }
        public int SoLuong { get; set; }
        public double GiaBan { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
