//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thu_project2_cnt1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.DONHANGCTs = new HashSet<DONHANGCT>();
        }
    
        public int MaDonHang { get; set; }
        public int MaUser { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public double TongTien { get; set; }
        public string TrangThai { get; set; }
        public string DiaChiNhan { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANGCT> DONHANGCTs { get; set; }
    }
}
