//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thu_project2_cnt1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANTRI
    {
        public int MaQT { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
